"""User-facing strings and input labels for the floating panel."""

from __future__ import annotations


TRANSLATIONS = {
    "fr": {
        "settings": "PARAMÈTRES",
        "layout": "DISPOSITION",
        "language": "LANGUE",
        "previous_key": "TOUCHE PRÉCÉDENTE",
        "next_key": "TOUCHE SUIVANTE",
        "replication_mode": "MODE RÉPLICATION",
        "group_leader": "CHEF DU GROUPE",
        "group_leader_info": (
            "Si vous changez le chef du groupe après le lancement ou après le "
            "premier chargement, le changement sera appliqué au prochain chargement."
        ),
        "lock": "VERROUILLER",
        "position": "Position",
        "icons": "Icônes",
        "play_button": "BOUTON PLAY",
        "enabled": "Activé",
        "scale": "ÉCHELLE",
        "opacity": "TRANSPARENCE",
        "save": "ENREGISTRER",
        "press_input": "APPUYEZ…",
        "input_prompt": "CLAVIER, SOURIS OU MOLETTE…",
        "offline": "{player} hors ligne",
        "no_window": "AUCUNE FENÊTRE",
        "replication_no_target": "RÉPLICATION ACTIVÉE · AUCUNE CIBLE",
        "replication_targets": "RÉPLICATION ACTIVÉE · {count} CIBLES",
        "replication_disabled": "RÉPLICATION DÉSACTIVÉE",
        "action_running": "ACTION EN COURS",
        "starting": "LANCEMENT…",
        "stop_hint": "CTRL+Q · ARRÊTER",
        "stopping": "ARRÊT EN COURS…",
        "cancelled": "ACTION ARRÊTÉE",
        "listener_unavailable": "ÉCOUTEUR INDISPONIBLE: {devices}",
        "replication_error": "RÉPLICATION: {error}",
        "done": "TERMINÉ",
        "error": "ERREUR",
        "update_available": "MISE À JOUR DISPONIBLE",
        "update_message": "La version {version} est disponible. Voulez-vous l’installer maintenant ?",
        "update_now": "METTRE À JOUR",
        "update_later": "PLUS TARD",
        "update_downloading": "TÉLÉCHARGEMENT DE LA MISE À JOUR…",
        "update_failed": "ÉCHEC DE LA MISE À JOUR: {error}",
        "close_settings": "FERMER LES PARAMÈTRES",
        "minimize_app": "RÉDUIRE L’APPLICATION",
        "show_app": "AFFICHER L’APPLICATION",
        "quit_app": "QUITTER L’APPLICATION",
    },
    "en": {
        "settings": "SETTINGS",
        "layout": "LAYOUT",
        "language": "LANGUAGE",
        "previous_key": "PREVIOUS WINDOW",
        "next_key": "NEXT WINDOW",
        "replication_mode": "REPLICATION MODE",
        "group_leader": "GROUP LEADER",
        "group_leader_info": (
            "If you change the group leader after launching or after the first "
            "load, the change will be applied on the next load."
        ),
        "lock": "LOCK",
        "position": "Position",
        "icons": "Icons",
        "play_button": "PLAY BUTTON",
        "enabled": "Enabled",
        "scale": "SCALE",
        "opacity": "OPACITY",
        "save": "SAVE",
        "press_input": "PRESS A KEY…",
        "input_prompt": "KEYBOARD, MOUSE, OR WHEEL…",
        "offline": "{player} offline",
        "no_window": "NO WINDOW",
        "replication_no_target": "REPLICATION ENABLED · NO TARGET",
        "replication_targets": "REPLICATION ENABLED · {count} TARGETS",
        "replication_disabled": "REPLICATION DISABLED",
        "action_running": "ACTION IN PROGRESS",
        "starting": "STARTING…",
        "stop_hint": "CTRL+Q · STOP",
        "stopping": "STOPPING…",
        "cancelled": "ACTION STOPPED",
        "listener_unavailable": "INPUT LISTENER UNAVAILABLE: {devices}",
        "replication_error": "REPLICATION: {error}",
        "done": "DONE",
        "error": "ERROR",
        "update_available": "UPDATE AVAILABLE",
        "update_message": "Version {version} is available. Install it now?",
        "update_now": "UPDATE NOW",
        "update_later": "LATER",
        "update_downloading": "DOWNLOADING UPDATE…",
        "update_failed": "UPDATE FAILED: {error}",
        "close_settings": "CLOSE SETTINGS",
        "minimize_app": "MINIMIZE APPLICATION",
        "show_app": "SHOW APPLICATION",
        "quit_app": "QUIT APPLICATION",
    },
}

LANGUAGE_LABELS = {"fr": "Français", "en": "English"}

INPUT_NAME_EN = {
    "CLAVIER": "KEYBOARD",
    "SOURIS": "MOUSE",
    "SOURIS GAUCHE": "LEFT MOUSE",
    "SOURIS DROITE": "RIGHT MOUSE",
    "SOURIS MILIEU": "MIDDLE MOUSE",
    "SOURIS 4": "MOUSE 4",
    "SOURIS 5": "MOUSE 5",
    "MOLETTE HAUT": "WHEEL UP",
    "MOLETTE BAS": "WHEEL DOWN",
    "MOLETTE DROITE": "WHEEL RIGHT",
    "MOLETTE GAUCHE": "WHEEL LEFT",
    "RETOUR ARRIÈRE": "BACKSPACE",
    "ENTRÉE": "ENTER",
    "MAJ": "SHIFT",
    "VERR MAJ": "CAPS LOCK",
    "ESPACE": "SPACE",
    "FIN": "END",
    "DÉBUT": "HOME",
    "GAUCHE": "LEFT",
    "HAUT": "UP",
    "DROITE": "RIGHT",
    "BAS": "DOWN",
    "IMPR ÉCRAN": "PRINT SCREEN",
    "SUPPR": "DELETE",
    "WINDOWS GAUCHE": "LEFT WINDOWS",
    "WINDOWS DROITE": "RIGHT WINDOWS",
    "VERR NUM": "NUM LOCK",
    "ARRÊT DÉFIL": "SCROLL LOCK",
    "MAJ GAUCHE": "LEFT SHIFT",
    "MAJ DROITE": "RIGHT SHIFT",
    "CTRL GAUCHE": "LEFT CTRL",
    "CTRL DROITE": "RIGHT CTRL",
    "ALT GAUCHE": "LEFT ALT",
    "ALT DROITE": "RIGHT ALT",
    "NAV PRÉCÉDENT": "BROWSER BACK",
    "NAV SUIVANT": "BROWSER FORWARD",
    "NAV ACTUALISER": "BROWSER REFRESH",
    "MUET": "MUTE",
    "MÉDIA SUIVANT": "NEXT TRACK",
    "MÉDIA PRÉCÉDENT": "PREVIOUS TRACK",
    "MÉDIA STOP": "STOP MEDIA",
    "MÉDIA PLAY/PAUSE": "PLAY/PAUSE MEDIA",
}


def translate(language: str, key: str, **values: object) -> str:
    """Return a localized UI string and fall back to French."""
    locale = language if language in TRANSLATIONS else "fr"
    template = TRANSLATIONS[locale].get(key, TRANSLATIONS["fr"].get(key, key))
    return template.format(**values)
